
services:
  nodebb:
    container_name: amnesia_forum
    build: .
    restart: unless-stopped
    ports:
      - '4567:4567'
    volumes:
      - ./.docker/build:/usr/src/app/build
      - ./.docker/uploads:/usr/src/app/public/uploads
      - ./.docker/config:/opt/config
    platform: linux/amd64
    networks:
      - outside

  postgres:
    image: postgres:16.3-alpine
    container_name: amnesia-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: nodebb
      POSTGRES_PASSWORD: qDu9sUE4eC4y2u
      POSTGRES_DB: amnesia
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    platform: linux/amd64
    networks:
      - outside
    ports:
      - '5444:5432'

  
networks:
  outside:
